name = "curriculum-demo-api"
main = "src/index.ts"
compatibility_date = "2026-06-01"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "78b3533c861644bcb172489226f63b5c"

[vars]
ALLOWED_ORIGIN = "https://imsherlocked27.github.io"
OPENAI_MODEL = "gpt-4o-mini"
